spring:
    url: "jdbc:mysql://localhost/test"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: AbdielEstudos
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /livraria